#include "Tasks.h"

command script[] = {
	{ NOTHING , 200},
	{ TRIGGERS,   5},
	{ NOTHING ,   5},
	{ NOTHING , 100},
	{ TRIGGERS,   5},
	{ NOTHING ,   5},
	{ NOTHING , 100},
	{ NOTHING ,   1},
	{ NOTHING ,   1},
	{ NOTHING ,   1},
	{ NOTHING ,   1},
	{ NOTHING ,   1},
	{ NOTHING ,   1},
	{ LEFT    ,   5},
	{ NOTHING ,   5},
	{ A       ,   5},
	{ NOTHING ,  50},
	{ A       ,   5},
	{ NOTHING , 200},
	{ B       ,   5},
	{ NOTHING ,   5},
	{ NOTHING , 100},
	{ B       ,   5},
	{ NOTHING ,  25},
	{ B       ,   5},
	{ NOTHING ,  25},
	{ DOWN    ,  25},
	{ NOTHING ,  25},
	{ RIGHT   , 250},
	{ NOTHING ,  25},
	{ NOTHING ,  25},
	{ LEFT    , 250},
	{ NOTHING ,  25},
	{ UP      ,  50},
	{ NOTHING ,  25},
};